### ISSUE TITLE
Job Finding Website

### ISSUE THREAD

**Issue by apu52** [avinash201199/Your-Projects#10]
# Introduction

Hello Sir,
I want to add my project as job finding website.
This repo includes 
- Job Search
- Internship Listings
- Company Profiles
- Performance Tracking
- Bookmarks and Notifications
- User Accounts
- Mobile Responsiveness

# Screenshot

![image](https://github.com/avinash201199/Your-Projects/assets/114172928/f2d0a58b-3432-4403-baa5-857226f8848b)

# Additional Context

Please assign me this issue under OSEN

**Comment by apu52** [comment]
@avinash201199 @Shu12388y Please assign me this issue under OSEN

**Comment by Shu12388y** [comment]
@Shu12388y start working
