### ISSUE TITLE
Hotstar Clone

### ISSUE THREAD

**Issue by apu52** [avinash201199/Your-Projects#11]
# Introduction
Hello Sir, 
I want to add my Hotstar Clone project in this repo
# Screenshots

![image](https://github.com/avinash201199/Your-Projects/assets/114172928/d53ea3b2-c7be-4c89-8c2f-1e8d003dc7f5)

# Additional Context
Please Assign me this issue under OSEN

**Comment by apu52** [comment]
@avinash201199 @Shu12388y Please assign me this issue under OSEN

**Comment by Shu12388y** [comment]
@apu52 start working
