### ISSUE TITLE
Scientific Calculator

### ISSUE THREAD

**Issue by apu52** [avinash201199/Your-Projects#15]
# Introduction
 Hello sir,
I want to add my project of Scientific calculator in this repo.

# Screenshots
https://github.com/apu52/Scientific-Calculator/assets/114172928/2cfa1956-4af8-4a90-aebf-4beff47fc4f0

# Additional Context
Please assign me this issue under OSEN

**Comment by apu52** [comment]
@Shu12388y @avinash201199 Please assign me this issue.

**Comment by Shu12388y** [comment]
@apu52 start working
