### ISSUE TITLE
Temperature Converter

### ISSUE THREAD

**Issue by apu52** [avinash201199/Your-Projects#16]
# Introduction

Hello sir,
I want to add my project on Temperature converter.

# Video

https://user-images.githubusercontent.com/114172928/252881128-266bcd52-a059-4875-89f4-50bbac58aed9.mp4

# Additional Context

Please assign me this issue under OSEN.

**Comment by apu52** [comment]
@avinash201199 @Shu12388y Please assign me this issue under OSEN.

**Comment by Shu12388y** [comment]
@apu52 start working
