### ISSUE TITLE
URL SHORTENER PROJECT

### ISSUE THREAD

**Issue by Geeks-Arpan** [avinash201199/Your-Projects#17]
Title: URL SHORTENER PROJECT
I want to add my URL SHORTENER project.
SCREENSHORT
![Front Page](https://github.com/avinash201199/Your-Projects/assets/99377659/3d92019c-9c2a-40ce-8c01-c47b7977eb7d)
Please assign me under OSEN program.

**Comment by Shu12388y** [comment]
@Geeks-Arpan start working
