### ISSUE TITLE
Text to Voice Converter

### ISSUE THREAD

**Issue by Geeks-Arpan** [avinash201199/Your-Projects#18]
Title: Text to Voice Converter

Tech Tools: Html,Css and Js

![Screenshot 2023-10-31 201328](https://github.com/avinash201199/Your-Projects/assets/99377659/09b9ff5e-4286-45bf-a5cf-bdc23bbd3afe)

Please assign me Under OSEN program.

**Comment by Shu12388y** [comment]
@Geeks-Arpan start working
