### ISSUE TITLE
Myntra Clone Website

### ISSUE THREAD

**Issue by Geeks-Arpan** [avinash201199/Your-Projects#33]
Title: Myntra Clone Website

Tech Tools: Html,Css and Js

**Screenshort**

![Screenshot 2023-10-29 112004](https://github.com/avinash201199/Your-Projects/assets/99377659/5d59d9a8-e546-4b8b-88c6-5e325bf6603e)
![Screenshot 2023-10-29 112032](https://github.com/avinash201199/Your-Projects/assets/99377659/19260a5e-cc30-4f8d-99fc-d8de83f1dceb)
![Screenshot 2023-10-29 112116](https://github.com/avinash201199/Your-Projects/assets/99377659/6fe92bae-03c0-4c4d-9dea-3567201de884)
![Screenshot 2023-10-29 112152](https://github.com/avinash201199/Your-Projects/assets/99377659/e2636c78-dd08-4c0f-b55a-33a56cadc644)
![Screenshot 2023-10-29 112221](https://github.com/avinash201199/Your-Projects/assets/99377659/c6d40b87-739c-416e-896a-bda12224006b)

Please assign me under OSEN

**Comment by Shu12388y** [comment]
@Geeks-Arpan start working
