### ISSUE TITLE
Travel frontend website

### ISSUE THREAD

**Issue by apu52** [avinash201199/Your-Projects#34]
Hello Sir,
I want to add my Travel frontend website in this repo.
Please assign me this issue so that I can work on this issue.

# Screenshot
![image](https://github.com/avinash201199/Your-Projects/assets/114172928/73ab1105-1014-4641-92d9-338b64b8f5bd)

**Comment by apu52** [comment]
@avinash201199 @Shu12388y Please assign me this issue

**Comment by Shu12388y** [comment]
@apu52 add a screenshot of the project

**Comment by apu52** [comment]
> @apu52 add a screenshot of the project

@Shu12388y I have added a SS of my project. Please assign it to me

**Comment by Shu12388y** [comment]
@apu52 start working
