### ISSUE TITLE
Music Player Clone Project

### ISSUE THREAD

**Issue by Geeks-Arpan** [avinash201199/Your-Projects#35]
Title: Music Player Clone Project

Tech Tools: Html,Css and Js

**Screenshort**
![Music-1](https://github.com/avinash201199/Your-Projects/assets/99377659/ccc2ce79-c56c-404d-85dc-5d604767e330)
![Music-2](https://github.com/avinash201199/Your-Projects/assets/99377659/8daf13d8-4084-491e-8828-11be080a408b)

Please assign me under OSEN

**Comment by Shu12388y** [comment]
@Geeks-Arpan start working
