### ISSUE TITLE
Netflix Clone

### ISSUE THREAD

**Issue by Geeks-Arpan** [avinash201199/Your-Projects#36]
Title: Netflix Clone

Tech Tools: Html,Css and Js

**Screenshort**

![Screenshot 2023-10-30 060943](https://github.com/Geeks-Arpan/Netflix_Clone.github.io/assets/99377659/058235be-d9d9-468c-86a6-b8978c7f6dc7)

Please assign me under OSEN

**Comment by Shu12388y** [comment]
@Geeks-Arpan start working
