### ISSUE TITLE
Insta frontend Clone

### ISSUE THREAD

**Issue by apu52** [avinash201199/Your-Projects#45]
Hello Sir,
I want to add my Insta Clone frontend project in this repo.

# Screenshot

![image](https://github.com/avinash201199/Your-Projects/assets/114172928/c6df647b-254c-406e-bd84-02a28a6c1822)

# Additional Context
Please assign me this issue under OSEN

**Comment by apu52** [comment]
@Shu12388y Please assign me this issue under OSEN

**Comment by Shu12388y** [comment]
@apu52 start working
