### ISSUE TITLE
Unit Converter Project

### ISSUE THREAD

**Issue by apu52** [avinash201199/Your-Projects#46]
Hello Sir,
I want to add my unit converter project in this repo.

# Screenshot
![image](https://github.com/avinash201199/Your-Projects/assets/114172928/ef6814dc-5840-4228-b333-3f016982647f)

# Additional Context

Sir please assign me to this issue

**Comment by apu52** [comment]
@avinash201199 @Shu12388y Please assign me this issue

**Comment by Shu12388y** [comment]
@apu52 start working
