### ISSUE TITLE
Inquiry Regarding Project Inclusion and Submission Process

### ISSUE THREAD

**Issue by k0msenapati** [avinash201199/Your-Projects#6]
What types of projects can be added here (vanilla JS, frameworks in Python/JS, or any other project)?

What is the procedure for adding a project? Do we need to raise an issue or submit a PR?

It would also be appreciated if you could explain the file structure.

**Comment by Shu12388y** [comment]
@kom-senapati you can add any project. First, create an issue in that issue mention your project, and add a screenshot after assigning the issue make a folder with your name and add your project in that folder add a readme file that contains about the project also add a screenshot  and your GitHub user name after that in the data folder there is data.json file fill the data in it
