### ISSUE TITLE
Random Recipe generator

### ISSUE THREAD

**Issue by k0msenapati** [avinash201199/Your-Projects#7]
The Random Recipe Generator is a web application that generates random recipes for users.

![image](https://github.com/avinash201199/Your-Projects/assets/92045934/07704468-59a6-48cb-afaf-67941f6396c2)

![image](https://github.com/avinash201199/Your-Projects/assets/92045934/67b515cb-30c5-46a5-afe4-1386de6a71be)

I would like to add this project to the repo.

**Comment by Shu12388y** [comment]
@kom-senapati start working
