### ISSUE TITLE
Food Website

### ISSUE THREAD

**Issue by apu52** [avinash201199/Your-Projects#9]
# Introduction
Hello Sir,
I want to add my new Food website project in this repo.
This project includes  contains my project on my Food Website😋. I have made it using HTML,CSS & JS. It contains a menu card of different cuisines such as Biriyani , Chinese, Paneer Mania, Veg as well as South Indian.🍕 .
 
# Screenshots

![image](https://github.com/avinash201199/Your-Projects/assets/114172928/3627f540-da58-4962-9d7f-0b27fb6a58f1)

# Additional Context

Please assign me this issue under OSEN (Collab-code Carnival)

**Comment by apu52** [comment]
@Shu12388y @avinash201199 Please assign me this issue under OSEN

**Comment by Shu12388y** [comment]
@apu52 start working
